checks:
    php:
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        remove_php_closing_tag: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        fix_php_opening_tag: true
        fix_identation_4spaces: true
        side_effects_or_types: true
        require_php_tag_first: true
        php5_style_constructor: true
        one_class_per_file: true
        no_global_keyword: true
        no_mixed_inline_html: true
        no_short_open_tag: true
        prefer_sapi_constant: true
        no_unnecessary_function_call_in_for_loop: true
        avoid_unnecessary_concatenation: true
        too_many_arguments: true
        encourage_shallow_comparison: true
        switch_fallthrough_commented: true
        phpunit_assertions: true
        non_commented_empty_catch_block: true
        no_goto: true
        avoid_usage_of_logical_operators: true
        no_eval: true
        no_unnecessary_if: true
        no_unnecessary_final_modifier: true
        no_empty_statements: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        spacing_of_function_arguments: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        space_after_cast: true
        single_namespace_per_use: true
        simplify_boolean_return: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_braces_around_control_structures: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        prefer_while_loop_over_for_loop: true
        parameters_in_camelcaps: true
        properties_in_camelcaps: true
        optional_parameters_at_the_end: true
        no_underscore_prefix_in_properties: true
        no_space_inside_cast_operator: true
        no_space_before_semicolon: true
        no_space_around_object_operator: true
        no_error_suppression: true
        no_commented_out_code: true
        lowercase_php_keywords: true
        lowercase_basic_constants: true
        function_in_camel_caps: true
        function_body_start_on_new_line: true
        ensure_lower_case_builtin_functions: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        blank_line_after_namespace_declaration: true
        avoid_tab_indentation: true
        avoid_multiple_statements_on_same_line: true
        avoid_closing_tag: true
        avoid_aliased_php_functions: true
        align_assignments: true
filter:
    excluded_paths:
        - tests/*
        - vendor/*
tools:
    external_code_coverage:
        timeout: 300   # How long should we wait for code coverage (in seconds).
        runs: 1        # In how many runs have you split your tests?
    php_sim: true
    php_pdepend: true
    php_analyzer: true