language: php
php:
  - 7.0
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
install:
  - composer self-update
  - composer install
script: vendor/bin/phpunit
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.xml