language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
install:
  - composer self-update
  - composer install
script: phpunit --coverage-clover=coverage.clover --bootstrap vendor/autoload.php tests
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover